package com.blueskyminds.framework;

/**
 * An exception generated by a service during initialisation
 *
 * Date Started: 14/01/2007
 * <p/>
 * History:
 * <p/>
 * Copyright (c) 2007 Blue Sky Minds Pty Ltd<br/>
 */
public class ServiceInitialisationException extends Exception {

    // ------------------------------------------------------------------------------------------------------

    /**
     * Initialise the ServiceInitialisationException with default attributes
     */
    private void init() {
    }

    // ------------------------------------------------------------------------------------------------------

    public ServiceInitialisationException() {
    }

    public ServiceInitialisationException(String message) {
        super(message);
    }

    public ServiceInitialisationException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceInitialisationException(Throwable cause) {
        super(cause);
    }
}
